/* Separate mail folders and per-message actions */
state.nav = 'Inbox';
state.drafts = [];
const refreshMessages = refresh;
window.refresh = async function(){const data=await api('/messages');state.messages=data.messages;state.drafts=data.drafts||[]};
window.conversations = function(){
  if(state.nav==='Drafts') return state.drafts.map(d=>({key:'draft:'+d.id,peers:d.to||[],last:{...d,from:'self',body:d.body||'',subject:d.subject||''},items:[],draft:true,draftData:d}));
  const groups={};
  for(const m of state.messages){if((m.folder||'Inbox')!==state.nav)continue;const fromSelf=m.from==='self'||m.from===state.user?.phone;let peers=fromSelf?m.to.filter(x=>x!=='self'&&x!==state.user?.phone):[m.from];if(!peers.length)peers=['self'];const key=peers.slice().sort().join('|');(groups[key]??={key,peers,last:m,items:[]}).items.push(m)}
  return Object.values(groups).sort((a,b)=>b.last.time-a.last.time)
};
window.renderList = function(){
  let list=conversations(),q=state.query.toLowerCase();
  list=list.filter(c=>{let m=c.last,person=c.draft?(m.subject||c.peers.map(human).join(', ')||'Untitled draft'):c.peers.map(human).join(', ');let match=person.toLowerCase().includes(q)||m.subject.toLowerCase().includes(q)||m.body.toLowerCase().includes(q);let unread=c.items.some(x=>x.unread&&x.from!=='self');let f=state.filter==='All'||state.filter==='Unread'&&unread||state.filter==='Attachments'&&c.items.some(x=>x.attachments?.length)||state.filter==='Favorites'&&c.items.some(x=>x.favorite);return match&&f});
  $('#chat-list').innerHTML=list.map(c=>{let m=c.last,unread=c.items.filter(x=>x.unread&&x.from!=='self').length,person=c.draft?(m.subject||c.peers.map(human).join(', ')||'Untitled draft'):c.peers.map(human).join(', ');return `<div class="chat-item ${state.active===c.key?'selected':''}" data-key="${esc(c.key)}"><div class="avatar" style="background:${colors[c.key.length%colors.length]}">${c.draft?'▧':esc(initials(person))}</div><div class="chat-copy"><div class="chat-line"><span class="chat-name">${c.draft?'Draft · ':''}${esc(person)}</span><span class="chat-time">${time(m.time)}</span></div><div class="chat-line"><span class="chat-preview ${unread?'unread':''}">${esc((m.from==='self'||m.from===state.user?.phone?'You: ':'')+m.body)}</span><span class="chat-meta">${m.important?'❗':m.favorite?'☆':''}${unread?`<i class="unread-badge">${unread}</i>`:''}</span></div></div></div>`}).join('')||`<div class="folder-empty"><span>${state.nav==='Inbox'?'✉':state.nav==='Drafts'?'▧':state.nav==='Spam'?'◉':'▱'}</span><b>${state.nav==='Inbox'?'Your inbox is clear':state.nav==='Drafts'?'No drafts yet':state.nav==='Spam'?'No spam here':'Trash is empty'}</b><small>${state.nav==='Inbox'?'Messages will appear here.':state.nav==='Drafts'?'Saved drafts will appear here.':state.nav==='Spam'?'Messages moved to spam will appear here.':'Messages moved to trash will appear here.'}</small></div>`;
  $$('.chat-item').forEach(e=>e.onclick=()=>{const c=list.find(x=>x.key===e.dataset.key);if(c?.draft)compose(c.draftData);else openChat(e.dataset.key)});
  $('#list-heading').textContent=state.nav.toUpperCase();const unread=state.messages.filter(x=>(x.folder||'Inbox')==='Inbox'&&x.unread&&x.from!=='self').length;$('#unread-count').textContent=unread||'';$$('.rail-icon[data-folder]').forEach(b=>b.classList.toggle('active',b.dataset.folder===state.nav));
};
window.renderMessages = function(c){
  $('#messages').innerHTML='<div class="date-pill">TODAY, A LITTLE MORE CONNECTED</div>'+c.items.sort((a,b)=>a.time-b.time).map(m=>{const mine=m.from==='self'||m.from===state.user?.phone,reply=m.replyTo&&state.messages.find(x=>x.id===m.replyTo),mayReply=!mine&&!state.messages.some(x=>x.replyTo===m.id),folder=m.folder||'Inbox';return `<article class="message ${mine?'mine':''}"><div class="message-head">${mine?'You':esc(human(m.from))}</div><div class="bubble">${m.subject&&!reply?`<div class="bubble-subject">${esc(m.subject)}</div>`:''}${reply?`<div class="quoted">↳ ${esc(human(reply.from))}: ${esc(reply.body.slice(0,85))}</div>`:''}${esc(m.body)}${(m.attachments||[]).map(a=>`<div class="attachment">⌁ &nbsp;${esc(a.name)} · ${esc(a.size)}</div>`).join('')}</div><div class="message-foot">${time(m.time)} ${mine?'✓✓':''}</div><div class="message-tools">${mayReply?`<button data-reply="${m.id}" title="Reply">↩</button>`:''}<button data-fav="${m.id}" title="Favorite">${m.favorite?'★':'☆'}</button><div class="message-menu-wrap"><button class="menu-trigger" title="Email actions" aria-label="Email actions">⋮</button><div class="message-dropdown">${folder!=='Inbox'?`<button data-move="Inbox" data-id="${m.id}">Move to inbox</button>`:''}${folder!=='Trash'?`<button data-move="Trash" data-id="${m.id}">Move to trash</button>`:''}${folder!=='Spam'?`<button data-move="Spam" data-id="${m.id}">Move to spam</button>`:''}<button data-important="${m.id}">${m.important?'Remove importance':'Mark as important'}</button></div></div></div></article>`}).join('');
  $$('[data-reply]').forEach(b=>b.onclick=()=>setReply(b.dataset.reply));
  $$('[data-fav]').forEach(b=>b.onclick=async()=>{const m=state.messages.find(x=>x.id===b.dataset.fav);m.favorite=!m.favorite;await api('/mark',{id:m.id,field:'favorite',value:m.favorite});renderMessages(c);renderList()});
  $$('[data-important]').forEach(b=>b.onclick=async()=>{const m=state.messages.find(x=>x.id===b.dataset.important);m.important=!m.important;await api('/mark',{id:m.id,field:'important',value:m.important});await refresh();const current=conversations().find(x=>x.key===state.active);if(current)renderMessages(current);renderList()});
  $$('[data-move]').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,target=b.dataset.move;try{await api('/mark',{id,field:'folder',value:target});await refresh();const current=conversations().find(x=>x.key===state.active);if(current)renderMessages(current);else{$('#conversation').classList.add('hidden');$('#welcome').classList.remove('hidden');$('#app').classList.remove('chat-open');state.active=null}renderList();toast(target==='Inbox'?'Moved to Inbox':`Moved to ${target}`)}catch(e){toast(e.message)}});
  $('#messages').scrollTop=$('#messages').scrollHeight;
};
window.compose = function(draft=null){const recipients=(draft?.to||[]).join(', ');modal(draft?'Edit draft':'Write a message',`<form id="compose-form" data-draft-id="${esc(draft?.id||'')}"><label>To <span style="font-weight:400;color:#96a29a">· phone number(s), comma separated</span></label><input name="to" value="${esc(recipients)}" placeholder="9876543210, 9876500000"><p class="modal-hint">More than one recipient starts a new group conversation. Use country code for international numbers.</p><label>Subject</label><input name="subject" value="${esc(draft?.subject||'')}" placeholder="What is this about?"><label>Message</label><textarea name="body" placeholder="Write something thoughtful...">${esc(draft?.body||'')}</textarea><div class="compose-actions"><button class="primary-btn" type="submit">Send message <span>➤</span></button><button class="secondary-btn" type="button" id="save-draft">Save to drafts</button></div></form>`);
  $('#compose-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),to=f.get('to').split(',').map(x=>x.trim()).filter(Boolean),body=f.get('body').trim();if(!to.length||!body){toast('Add a recipient and message before sending.');return}try{await api('/messages',{to,subject:f.get('subject'),body,draftId:e.target.dataset.draftId});closeModal();await refresh();renderList();toast('Message sent ✿')}catch(err){toast(err.message)}};
  $('#save-draft').onclick=async()=>{const f=new FormData($('#compose-form')),to=f.get('to').split(',').map(x=>x.trim()).filter(Boolean);try{await api('/drafts',{id:$('#compose-form').dataset.draftId,to,subject:f.get('subject'),body:f.get('body')});closeModal();await refresh();renderList();toast('Draft saved')}catch(err){toast(err.message)}};
};
function selectFolder(folder){state.nav=folder;state.filter='All';state.active=null;$$('.chip').forEach(b=>b.classList.toggle('active',b.dataset.filter==='All'));$('#app').classList.remove('chat-open');$('#conversation').classList.add('hidden');$('#welcome').classList.remove('hidden');renderList()}
$$('.rail-icon[data-folder]').forEach(b=>b.onclick=()=>selectFolder(b.dataset.folder));
$('#menu-toggle').onclick=()=>{modal('Your folders',`<div class="folder-picker"><button data-folder-choice="Inbox">✉ &nbsp; Inbox</button><button data-folder-choice="Drafts">▧ &nbsp; Drafts</button><button data-folder-choice="Spam">◉ &nbsp; Spam</button><button data-folder-choice="Trash">▱ &nbsp; Trash</button></div>`)};
$('#modal-card').addEventListener('click',e=>{const folderButton=e.target.closest('[data-folder-choice]');if(folderButton){selectFolder(folderButton.dataset.folderChoice);closeModal()}});

if(state.user)refresh().then(()=>renderList()).catch(()=>{});
